const quotes = [
  "Vyvyan! Where did you get that Howitzer from?",
  "Well he better be good this Norman Tebit",
  "This calls for a celebration! Vyv, throw another record player on the fire",
  "Bwilliant! Squatting! Youth contwol, no wrent!",
  "Hands up who likes me!",
  "I wouldn't eve discuss the colour of orange juice with you, Neil!",
  "Think once! Think twice! Think DON'T DRIVE YOUR CAR ON THE PAVEMENT!",
  "If you're going to be that sycophantic, why don't you go 'round there now and stick your tongue straight down the back of his trousers?",
  "Darling Fascist Bullyboy, Give me some more money, you bastard. May the seed of your loin be fruitful in the belly of your woman, Neil",
  "I'm so hungry I could eat my own ear wax. [to camera] And we all know how howwid that tastes, right, kids?",
  "You are cynically exploiting the fact that we've been beheaded so you can grab yourself a nicer bott!",
  "Join the pwefeshunels... It's great, you can have a gun if you want",
  "Yeah, that's what she said! You just can't trust women, can you?",
  "I hope you're satisfied, Thatcher!",
  "You won't catch me with me trousers!",
  "Don't tell them you're a pacifist!",
  "You know, I have the most terrible craving for a piece of fried lavatory paper.",
  "Open up, it's the pigs!",
  "Take the tit off your head!",
  "This is Starship Captain Warlock, on the planet Freakout, broadcasting to you on the inter-electric galactic airwaves",
  "We require ten assistants... Preferably Swedish!",
  "Yes, yes, that's fine, thank you very much, little old man, have a large sum of money",
  "Look what your rough-arm tactics have done, fascist!",
  "There's gonna be no chaise longues where you're going, Mikey boy!",
  "Shame about Cliff Richard",
  "I'm not a fridge, you know?",
  "Guys, there's some dinner on the floor if you want it",
  "Bad for society when the KIDS start to get into it!",
  "I might even be put in prison! And have water DRIPPED on my head!",
  "I will not be associated with saucers!",
  "You think I'm an aeroplane, don't you, Mike?",
  "Neil! Are these lentils South African?",
  "What are you doing, Neil? To make a meal, Neil? Surreal! From totalitarian vegetables! How much does it cost, Neil?",
  "I'm not paying you money to eat black men! I could become a pig and do that for free! Right on!",
  "Like, when the trap door opens, and I, like, die, it lights Joss Sticks and plays Rock Around The Clock it's totally amazing",
  "Oh, far out. Really great. WOODSTOCK!",
  "I'm supposed to write an essay on it, right, but... I think I'm just gonna stick it on the bonnet of my car!",
  "I think Special Patrol Group is a stupid name for a hamster!",
  "Well, let's put the rent up by a third!",
  "What that lad needs is a good hard DING DING!",
  "Hello, Mike, my little Thunderbird puppet! Thunderbirds are go, yes?",
  "I'm not really foreign, you know. I just do it to appear more sophisticated!",
  "Two men, Morcambe and Wise, yes? Funny comedians with the wigs and the buckets of water, yes?",
  "Is earthy English humor, yes? Like seaside postcard from Leicester, yes?",
  "Does this face empty knickers?",
  "It's a program for young adults, made by young adults, and concentratin' on all the subjects that young adults are into! Like, unemployment!",
  "Well I'm standing up here on this scaffolding because that's what this program is all about! Shock! Yeah! Right! Okay!",
  "But that doesn't mean I want you to seduce my parrot!",
  "Now what I think is if the kids are united, we will never be divided!",
  "Some of these bricks explode! That's good, innit?",
  "Stop making him pawanoid, you slag!",
  "Oh wow, I really hope we don't have a crash",
  "Well, I think it looks like a giant lavatory",
  "Neil, your bedroom's on fire!",
  "I don't have six pairs of hands, you know? I wish I had, but I haven't!",
  "You'd do anything to try and impress me, wouldn't you, Neil?",
  "Neil, let's not beat around the bush. Are you going to make supper, or am I going to kick your teeth in?",
  "I've got a stiff. Know what I mean?",
  "Oh, that's right, Neil, yeah! Lounge around! Have a good time, while we starve to death! Beatnik!",
  "Do you really think that anyone has ever been the slightest bit interested in anything you say or do ever, Neil?",
  "Five pounds to get in my own bedroom?! Hah! What have you done, turned it into a roller disco?",
  "Look, man. Either strut your stuff, or bug off!",
  "But listen, Guv'nor. This little Herbert was bothering the gentleman and the young ladies while they were shaking their booties to the ground. Know what I mean?",
  "What'd you just say? You just called me a bastard, didn't you?",
  "Listen, man. Sleep gives you cancer. Everyone knows that",
  "Listen, Neil. Do you know the difference between you and some number twos? Nothing!",
  "I'll teach you to try and assassinate the President!",
  "Haha! Missed both my legs!",
  "Viva El Presidente!",
  "Hello, are you the Czar?! Yes, I am, actually. Blam blam! Tough luck, fascist!",
  "My name is Alexei Yuri Gagarin Siege of Stalingrad Glorious Five-Year Plan Sputnik Pravda Moscow Dynamo Back Four Balowski. Me Dad was a bit of a Communist, know what I mean?",
  "Stuff the revolution. Where's my 200 quid?",
  "God, you'd think Devil Woman had never been written!",
  "Cornflakes. Cornflakes. Cornflakes, Cornflakes, Cornflakes. Cornflakes, Cornflakes, Cornflakes, Cornflakes!",
  "Oh, dear me! Poor old Neil's getting bored! The most boring person in the whole world is finally getting a taste of his own medicine!",
  "Guys! Guys! Look at us! Sqwabbling! Bickerwing, like children. What's happened to us? We never used to be like this!",
  "You have won second prize in a beauty contest! Smash Rick over the head with the bank",
  "Congratulations! It is your birthday! You may set fire to Rick's bed!",
  "Get out of Jail free! You may keep this card, sell it, or stick it up Rick's bottom!",
  "You know, living in a world where nothing boring ever happens can be a real pisser",
  "The King is bored shitless with interesting things, Minion, and so am I",
  "Ahem, don't worry, goldfish everywhere. I am in fact a stunt goldfish. In fact, by the time this program comes out, I will be doing the new James Bond film. So, there's no need to write in",
  "Oh, hello, pussycat! It's your Uncle Billy. Here! What you doin in a bucket?",
  "Come on, everybody, let's play Daleks! Exterminate! Exterminate! Exterminate! Exterminate!",
  "Are we ready, clocks?",
  "It sounds, right, it sounds like two elephants on a motorbike riding round and round, while a seal bangs a kipper on the table",
  "What is it now, Ralph?!?",
  "A man, believed to be a lunatic foreign terrorist, one of those greaseball raving reds who seem to crop up everywhere since we stopped running the world, is now taking refuge in an insanitary slum dwelling in North London",
  "They're dubbing that sound on! That's never real!",
  "Well, that's it. We're sorry we couldn't show you 'The Bastard Squad', but at least we got the mad coon with the gun, eh?",
  "You hum it, I'll smash your face in!",
  "Okay, I want a pint of water in a straight glass, a bag of roast ox crisps, and mine's a babysham!",
  "Ooer! He is a bastard, isn't he?",
  "Are you coming, Mike, or are you still talking to the old bag about your herpes?",
  "I reckon if I played me cards right I could have, you know...",
  "Neil? Have you just farted?",
  "Oh, look. A little girl! Meditate on this!",
  "Oh oh oh, don't we sound proper, Mr. Rasta's chocolate drop!",
  "That's white man's electricity you're burning ringing that doorbell. That's theft! I've got your number, so hold out your hand!",
  "Whose been gobbing in my lentils?",
  "Lads? It's two o'clock in the afternoon! Maybe it's time we got up!",
  "And was I consulted, pally? How do you think I feel stinking like a student's armpit?",
  "I know 'standing on the landing' may be a great song title, to me it's just a tax loss. So make space for the face that forced the abortion issue!",
  "That means we'll have to have raw tea again!",
  "Cornflakes for breakfast! That's disugsting, Neil!",
  "I wish I'd had time for a crap before we started!",
  "Oh, no. It's the holocaust!",
  "I'm going to form a new union society, right? With me a president! 'People Who Don't Pay Their TV Licenses Against the Nazis!",
  "If I had a penny for everytime I had to answer the door, I'd have five pound, sixty-three!",
  "I can't go to prison! I'm too pretty! I'll get raped!"
];

document.getElementById("new-quote").addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  document.getElementById("quote").textContent = quotes[randomIndex];
});











