const quotes = [
      "Vyvyan! Where did you get that Howitzer from?",
      "Well he better be good this Norman Tebit",
      "This calls for a celebration! Vyv, throw another record player on the fire",
      "Bwilliant! Squatting! Youth contwol, no wrent!",
      "Hands up who likes me!",
      "I wouldn't eve discuss the colour of orange juice with you, Neil!",
      "Think once! Think twice! Think DON'T DRIVE YOUR CAR ON THE PAVEMENT!",
      "If you're going to be that sycophantic, why don't you go 'round there now and stick your tongue straight down the back of his trousers?",
      "Darling Fascist Bullyboy, Give me some more money, you bastard. May the seed of your loin be fruitful in the belly of your woman, Neil",
      "I'm so hungry I could eat my own ear wax. [to camera] And we all know how howwid that tastes, right, kids?",
      "You are cynically exploiting the fact that we've been beheaded so you can grab yourself a nicer bott!",
      "Join the pwefeshunels... It's great, you can have a gun if you want",
      "Yeah, that's what she said! You just can't trust women, can you?",
      "I hope you're satisfied, Thatcher!",
      "You won't catch me with me trousers!",
      "Don't tell them you're a pacifist!",
      "You know, I have the most terrible craving for a piece of fried lavatory paper.",
      "Open up, it's the pigs!",
      "Take the tit off your head!",
      "This is Starship Captain Warlock, on the planet Freakout, broadcasting to you on the inter-electric galactic airwaves",
      "We require ten assistants... Preferably Swedish!",
      "Yes, yes, that's fine, thank you very much, little old man, have a large sum of money",
      "Look what your rough-arm tactics have done, fascist!",
      "There's gonna be no chaise longues where you're going, Mikey boy!",
      "Shame about Cliff Richard",
      "I'm not a fridge, you know?",
      "Guys, there's some dinner on the floor if you want it",
      "Bad for society when the KIDS start to get into it!",
      "I might even be put in prison! And have water DRIPPED on my head!",
      "I will not be associated with saucers!",
      "You think I'm an aeroplane, don't you, Mike?",
      "Neil! Are these lentils South African?",
      "What are you doing, Neil? To make a meal, Neil? Surreal! From totalitarian vegetables! How much does it cost, Neil?",
      "I'm not paying you money to eat black men! I could become a pig and do that for free! Right on!",
      "Like, when the trap door opens, and I, like, die, it lights Joss Sticks and plays "Rock Around The Clock"; it's totally amazing",
      "Oh, far out. Really great. WOODSTOCK!",
      "I'm supposed to write an essay on it, right, but... I think I'm just gonna stick it on the bonnet of my car!",
      "I think "Special Patrol Group" is a stupid name for a hamster!",
      "Well, let's put the rent up by a third!",
      "What that lad needs is a good hard DING DING!",
      "Hello, Mike, my little Thunderbird puppet! Thunderbirds are go, yes?",
      "I'm not really foreign, you know. I just do it to appear more sophisticated!",
      "Two men, Morcambe and Wise, yes? Funny comedians with the wigs and the buckets of water, yes?",
      "Is earthy English humor, yes? Like seaside postcard from Leicester, yes?",
      "Does this face empty knickers?",
      "It's a program for young adults, made by young adults, and concentratin' on all the subjects that young adults are into! Like, unemployment!",
      "Well I'm standing up here on this scaffolding because that's what this program is all about! Shock! Yeah! Right! Okay!",
      "But that doesn't mean I want you to seduce my parrot!",
      "Now what I think is if the kids are united, we will never be divided!",
      "Some of these bricks explode! That's good, innit?",
      "Oh, uh... I'm being hassled in the street by a chick!"
];

document.getElementById("new-quote").addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  document.getElementById("quote").textContent = quotes[randomIndex];
});
