const quotes = [
  "Vyvyan! Where did you get that Howitzer from?",
  "Well he better be good this Norman Tebit",
  "This calls for a celebration! Vyv, throw another record player on the fire",
  "Bwilliant! Sqwatting! Youth contwol, no went!",
  "Hands up who likes me!",
  "I wouldn't even discuss the colour of orange juice with you, Neil!",
  "Think once! Think twice! Think DON'T DRIVE YOUR CAR ON THE PAVEMENT!",
  "If you're gowing to be that sycophantic, why don't you go 'wound there now and stick your tongue stwaight down the back of his twousers?",
  "Darling Fascist Bullyboy, Give me some more money, you bastard. May the seed of your loin be fruitful in the belly of your woman, Neil",
  "I'm so hungwy I could eat my own ear wax. And we all know how howwid that tastes, right, kids?",
  "You are cynically exploiting the fact that we've been beheaded so you can grab yourself a nicer bott!",
  "Join the pwefeshunels... It's great, you can have a gun if you want",
  "Yeah, that's what she said! You just can't trust women, can you?",
  "I hope you're satisfied, Thatcher!",
  "You won't catch me with me trousers!",
  "Don't tell them you're a pacifist!",
  "You know, I have the most terrible craving for a piece of fried lavatory paper.",
  "Open up, it's the pigs!",
  "Take the tit off your head!",
  "This is Starship Captain Warlock, on the planet Freakout, broadcasting to you on the inter-electric galactic airwaves",
  "We require ten assistants... Preferably Swedish!",
  "Yes, yes, that's fine, thank you vewy much, little old man, have a large sum of money",
  "Look what your wuff-arm tactics have done, fascist!",
  "There's gonna be no chaise longues where you're going, Mikey boy!",
  "Shame about Cliff Wichard",
  "I'm not a fwidge, you know?",
  "Guys, there's some dinner on the floor if you want it",
  "Bad for society when the KIDS start to get into it!",
  "I might even be put in pwison! And have water DWIPPED on my head!",
  "I will not be associated with saucers!",
  "You think I'm an airwoplane, don't you, Mike?",
  "Neil! Are these lentils South African?",
  "What are you doing, Neil? To make a meal, Neil? Surweal! From totalitawian vegetables! How much does it cost, Neil?",
  "I'm not paying you money to eat black men! I could become a pig and do that for free! Wight on!",
  "Like, when the trap door opens, and I, like, die, it lights Joss Sticks and plays Rock Around The Clock it's totally amazing",
  "Oh, far out. Weally great. WOODSTOCK!",
  "I'm supposed to write an essay on it, right, but... I think I'm just gonna stick it on the bonnet of my car!",
  "I think Special Patwol Group is a stupid name for a hamster!",
  "Well, let's put the rent up by a third!",
  "What that lad needs is a good hard DING DING!",
  "Hello, Mike, my little Thunderbird puppet! Thunderbirds are go, yes?",
  "I'm not really foreign, you know. I just do it to appear more sophisticated!",
  "Two men, Morcambe and Wise, yes? Funny comedians with the wigs and the buckets of water, yes?",
  "Is earthy English humor, yes? Like seaside postcard from Leicester, yes?",
  "Does this face empty knickers?",
  "It's a program for young adults, made by young adults, and concentratin' on all the subjects that young adults are into! Like, unemployment!",
  "Well I'm standing up here on this scaffolding because that's what this program is all about! Shock! Yeah! Right! Okay!",
  "But that doesn't mean I want you to seduce my parrot!",
  "Now what I think is if the kids are united, we will never be divided!",
  "Some of these bricks explode! That's good, innit?",
  "Stop making him pawanoid, you slag!",
  "Oh wow, I really hope we don't have a crash",
  "Well, I think it looks like a giant lavatory",
  "Neil, your bedroom's on fire!",
  "I don't have six pairs of hands, you know? I wish I had, but I haven't!",
  "You'd do anything to try and impress me, wouldn't you, Neil?",
  "Neil, let's not beat around the bush. Are you going to make supper, or am I going to kick your teeth in?",
  "I've got a stiff. Know what I mean?",
  "Oh, that's right, Neil, yeah! Lounge around! Have a good time, while we starve to death! Beatnik!",
  "Do you weally think that anywon has ever been the slightest bit interested in anything you say or do ever, Neil?",
  "Five pounds to get in my own bedwoom?! Hah! What have you done, turned it into a woller disco?",
  "Look, man. Either strut your stuff, or bug off!",
  "But listen, Guv'nor. This little Herbert was bothering the gentleman and the young ladies while they were shaking their booties to the ground. Know what I mean?",
  "What'd you just say? You just called me a bastard, didn't you?",
  "Listen, man. Sleep gives you cancer. Everyone knows that",
  "Listen, Neil. Do you know the difference between you and some number twos? Nothing!",
  "I'll teach you to try and assassinate the President!",
  "Haha! Missed both my legs!",
  "Viva El Presidente!",
  "Hello, are you the Czar?! Yes, I am, actually. Blam blam! Tough luck, fascist!",
  "My name is Alexei Yuri Gagarin Siege of Stalingrad Glorious Five-Year Plan Sputnik Pravda Moscow Dynamo Back Four Balowski. Me Dad was a bit of a Communist, know what I mean?",
  "Stuff the revolution. Where's my 200 quid?",
  "God, you'd think Devil Woman had never been written!",
  "Cornflakes. Cornflakes. Cornflakes, Cornflakes, Cornflakes. Cornflakes, Cornflakes, Cornflakes, Cornflakes!",
  "Oh, dear me! Poor old Neil's getting bored! The most boring person in the whole world is finally getting a taste of his own medicine!",
  "Guys! Guys! Look at us! Sqwabbling! Bickerwing, like children. What's happened to us? We never used to be like this!",
  "You have won second prize in a beauty contest! Smash Rick over the head with the bank",
  "Congratulations! It is your birthday! You may set fire to Rick's bed!",
  "Get out of Jail free! You may keep this card, sell it, or stick it up Rick's bottom!",
  "You know, living in a world where nothing boring ever happens can be a real pisser",
  "The King is bored shitless with interesting things, Minion, and so am I",
  "Ahem, don't worry, goldfish everywhere. I am in fact a stunt goldfish. In fact, by the time this program comes out, I will be doing the new James Bond film. So, there's no need to write in",
  "Oh, hello, pussycat! It's your Uncle Billy. Here! What you doin in a bucket?",
  "Come on, everybody, let's play Daleks! Exterminate! Exterminate! Exterminate! Exterminate!",
  "Are we ready, clocks?",
  "It sounds, right, it sounds like two elephants on a motorbike riding round and round, while a seal bangs a kipper on the table",
  "What is it now, Ralph?!?",
  "A man, believed to be a lunatic foreign terrorist, one of those greaseball raving reds who seem to crop up everywhere since we stopped running the world, is now taking refuge in an insanitary slum dwelling in North London",
  "They're dubbing that sound on! That's never real!",
  "Well, that's it. We're sorry we couldn't show you 'The Bastard Squad', but at least we got the mad coon with the gun, eh?",
  "You hum it, I'll smash your face in!",
  "Okay, I want a pint of water in a straight glass, a bag of roast ox crisps, and mine's a babysham!",
  "Ooer! He is a bastard, isn't he?",
  "Are you coming, Mike, or are you still talking to the old bag about your herpes?",
  "I reckon if I played me cards right I could have, you know...",
  "Neil? Have you just farted?",
  "Oh, look. A little girl! Meditate on this!",
  "Oh oh oh, don't we sound proper, Mr. Rasta's chocolate drop!",
  "That's white man's electricity you're burning ringing that doorbell. That's theft! I've got your number, so hold out your hand!",
  "Whose been gobbing in my lentils?",
  "Lads? It's two o'clock in the afternoon! Maybe it's time we got up!",
  "And was I consulted, pally? How do you think I feel stinking like a student's armpit?",
  "I know 'standing on the landing' may be a great song title, to me it's just a tax loss. So make space for the face that forced the abortion issue!",
  "That means we'll have to have raw tea again!",
  "Cornflakes for breakfast! That's disugsting, Neil!",
  "I wish I'd had time for a crap before we started!",
  "Oh, no. It's the holocaust!",
  "I'm going to form a new union society, right? With me a president! 'People Who Don't Pay Their TV Licenses Against the Nazis!",
  "If I had a penny for everytime I had to answer the door, I'd have five pound, sixty-three!",
  "I can't go to prison! I'm too pretty! I'll get raped!",
  "Lads, I've told we don't have a telly and I think that's thrown him a bit, but it won't hold him forever!",
  "It was the other three, not me. I had no idea what was going on, it really was the other three!",
  "Well, it's better than playing with yourself! Ho ho! A cheap sexual illusion, makes the world go round!",
  "Bastard's the name! But you can call me right bleeding, all my friends do, or did",
  "As the eunuch said to Mussolini, 'I haven't got one, and if I did, I wouldn't show it to you!",
  "The old trick, eh? Eat the telly before I get a chance to nick you!",
  "It's a toaster!",
  "I know how to wait! And I promise you, son, when that telly comes out the other end, you're nicked!",
  "It's alright, lads! I always poo before I get up!",
  "I'm going upstairs to get the incredibly helpful and informative 'Protect and Survive' manual! Nobody better touch this while I'm gone!",
  "Why won't it go off, Mike?",
  "For someone who actually believes the lyrics to 'Devil Woman' have got something to say!",
  "Well, I'm going to tell Thatcher that we've got a bomb. And if she doesn't do something to help 'the kids' by this afternoon, we're going to blow up England!",
  "If people weren't sick, we wouldn't need penicillin!",
  "I won't say anything becasue no one ever listens to me anyway! I might as well be a Leonard Cohen record!",
  "So, is that the atom bomb is it, eh? Oooh, Naaaa, not in that colour, you know what I mean?",
  "Laugh? Laugh, I nearly went to Ethiopia. Second class of course!",
  "You're a right little five speed gearbox aren't you?",
  "You should have been here earlier, I holed in one! Mind you, I was playing pinball in the clubhouse!",
  "I'm tying my dog to the railroad track. Choo-choo train's gonna break his back",
  "Well Ive got news for you. I think old people are really boring and the only reason you don't understand our music is because you don't like it!",
  "Nothing but scroungers and horrid old people and workshy layabouts all wandering around clutching their Giros' and trying to get something for nothing",
  "Thatcher, Weve got a bomb, do what we want, or well blow it up. Signed, Anon",
  "A man with a handhul of takeaways is either very hungry, or knows someone that's very hungry",
  "There, that's all taken care off. By this time tomorrow everybody will be free and there will be no more racial prejudice or hatred! Get up, Neil! I hate you!",
  "Ya bunch of lavatory bowls!",
  "I hope this isn't a dud!",
  "I know, drape Neil over it! It might sort of cover up the blast!",
  "I thought the vacuum cleaner looked a bit on the tentative side so I souped it up a bit",
  "It's a hippie, isn't it. Tell it to get out. This isn't a Youth Hostel, you know?",
  "The BBC would like to warn all small children that pushing people inside old fridges is a bloody stupid thing to do!",
  "Don't eat all the Cornflakes, Rik, there's only one each!",
  "There's plenty of henna dip, Rik",
  "Have you said yes, hippie?",
  "Ah! A locust!",
  "Behold! The beast!",
  "Behold Armageddon, and the Four Horsemen of the Apocalypse. Famine, Pestilence, Death... and the other one",
  "Is that a seagull? Tell me, is that seagull a seagull?",
  "Microchip technology - that's quite a new thing, isn't it?",
  "I'll be dead soon if I don't get something to eat. How about a bloody sandwich?",
  "I beheld a medium sized group of people running around madly, waving their hands and shrieking ‘Twelve score oxen have spent over a year in the same field!",
  "Well that's just typical! Five minutes to go to the most important party of my life and half the house has been wrecked by a gigantic sandwich!",
  "Shut up, you girl!",
  "OK, pop music - lets go! Anyone here like the Human League?",
  "It's a telescope - a telescope with a mouse in it - bwilliant!",
  "I blew up a rubber johnny actually in the union bar. It was hilarious - everybody thought so",
  "I don't think we're gonna get in. I think it's a hippie?",
  "That's nothing. I kissed two girls on the lips last week!",
  "Hi, I'm Colin, from Ent. and I've been appointed by the social sector as joke compiler for this year's rag mag. Do you know any good jokes? It's for charity, you know!",
  "No, no! In the pit!",
  "Being Scottish and Jewish: two racial stereotypes for the price of one, perhaps the best value in the graveyard this morning. Perhaps not. Incidentally, just let me say how pleased I am to be here in the graveyard, where so many other comedians have died before me",
  "God, I'm bored! I might as well be listening to Genesis!",
  "It's called, 'SS Death Camp Criminal Battalion go to Monte Casino for the Massacre'",
  "For one man to love another, Vyvyan, is not poofy. It's actually very beautiful. It's only when they start touching each others bottoms that it gets poofy",
  "Dan Dare touches The Mekon's bottom!' 'Exciting new story: Batman gooses the Joker's crack!",
  "What do you think you're doing, pig? THWACK! Do you really give a fig, pig? BAM! And what's your favourite sort of gig, pig? Barry Manilow or the Black and White Minstrel Show? BOKKO!",
  "Yeah, where's the bloody vindaloo, hippie?",
  "Everything! Right. Lentils... wallpaper...",
  "You know, I just bet a bit later on somebody does drink that and turns into an axe-wielding, homicidal maniac!",
  "This may sound like a stupid question: Lip nip nip nip bip?",
  "People like you should be put in little boxes, tied up with string, and left in small dark rooms with out any electricity! For a month!",
  "Shirley? Is that your name, then? Shirley?",
  "Oh! Coca-Cola! Symbol of free West! Oh!  Oh, I like Coca-Cola",
  "That's just typical of you, Vyvyan! The house is under fifty feet of water and what do you do, build a submarine!",
  "Scaredy cat, scaredy cat! Sitting on the doormat! All the little doggie-wogs... will have a little bit of it...",
  "Oh, not that speaker! Jimi Hendrix once pissed on that!",
  "Answer the phone, Neil!",
  "Hands up, who likes me!",
  "Vyv, Vyv, uh, can you, like, actually kill yourself with laxative pills?",
  "This house will become a shrine! And punks and skins and Rastas will all gather round and all hold their hands in sorrow for their fallen leader! And all the grown-ups will say, 'But why are the kids crying?' And the kids will say, 'Haven't you heard? Rick is dead! The People's Poet is dead!",
  "Don't look at me, I'm irrelevant",
  "Vyvyan, please! Will you both please try and grow up and pay attention? It's my story, it's bloody amusing...Honestly, I don't know why I bother, sometimes!",
  "You haven't got a sister, Rick! You're the classic example of an only child!",
  "Amazing! Absolutely amazing. Human beings the size of amoebas",
  "Help! I'm being hassled by a killer sock!",
  "Socks aren't vegetables, man, they should be wiped out!",
  "As the one guy said to the other guy when he was getting fed up, I'm getting fed up. I want to wash my smalls, and I don't mean dip my tiddlies in a glass of water. ",
  "This calls for a very special blend of psychology and extreme violence",
  "You know what they say, 'dirty pants, clean botty!'",
  "Dirty duvet, dirty mind!",
  "My knickers are so old, it's only the stubborn understains that are holding them together!",
  "I like my bottom spotty!",
  "Oh, cock-a-doodle-doo, Neil! What are you talking about?",
  "Swotting away for teacher like a total spazmo!",
  "I'm asking you to test me on it, not throw up on it!",
  "Prick is a wonker. Signed, the rest of the class",
  "Shut up AND tell you the answer?",
  "Crop rotation in the 14th century was considerably more widespread after John?",
  "Do Not Lean Out of the Window. I wonder why?",
  "You've got your Garibaldi, of course, you've got your Bourbons, then of course you've got your Peek Freens Trotsky Assortment",
  "Revolutionary biscuits of Italy / Rise up out of your box! / You have nothing to lose but your wafers / Yum yum yum yum yum!",
  "All you get from a public school, right... one, you get a top job, right, and two, you get an interest in perverse sexual practices!",
  "Rah, rah, rah, we're going to smash the oiks!",
  "Well, I'm alright, 'cause my Daddy's bought me the Socialist Workers' Party for my birthday!",
  "Do you think they really do make it out of babies?",
  "Beep beep beep, oh no heavy, the coins keep coming out, beep beep beep, even the telephone hates me, beep beep beep, I wish there were no machines, and everyone led a pastoral existence, trees and flowers don't deliberately cool you out and go beep in your ear",
  "I liked the bit where you shoved the drill in the virgin otter's face!",
  "Bambi Goes Crazy Ape Bonkers with His Drill and Sex",
  "No, of course not, the posh kids win, they always do. Come on!",
  "See you, teddy-bear, come 'ere!",
  "Vegetable rights and peace!",
  "Alright, now, eh, wasn't it, wasn't it Monk d'Wally d'Honque?",
  "Certainly, will fifty pounds do?",
  "Buzz, buzz...uh, sorry to hassle you or anything, Bambi, but I really do need to go to the toilet really badly, you know?",
  "Oh, no, guys, I'm just going to have to wee on Lord Snot's head!",
  "Who said, 'Lawks a lordy, my bottom's on fire'?",
  "I've got a Porsche!",
  "Daddy sends hugs!",
  "We're getting trashed, we're getting completely trashed! Isn't there some way we can cheat?",
  "Give us some easy ones, Bambi, you big bottom-boil!",
  "What is the record number of marshmallows stuffed up one nostril?",
  "I told you that, Mike, you bloody cheat!",
  "Oh no, this sticky-bun's covered with human beings the size of amoebas. Here, Jumbo, get that through your esophagus",
  "You should have heard me at the undertakers, Mike! [[Snort!]] I made all these fabulous jokes about the undertaker coming 'round to measure my stiffie!",
  "When my hamster finds out you've nicked his carrot, he's gonna kill you Neil",
  "He doesn't eat carrots, Neil! He sticks 'em down his underpants to impress the girls!",
  "Do you dig graves?",
  "What's this camera? Is this Game For A Laugh? Have you killed someone as a prank?",
  "Neil! The bathrooms free! Unlike the country under the Thatcher-ite junta!",
  "What do you know about the beans?",
  "Oh come off it Neil! Where's your spunk?!",
  "What are you planning to do, photosynthesise?",
  "Yes, we've got a video!",
  "Oh, touche, Vyvyan. What devastating repartee. Talk about Oscar Wilde",
  "Don't you dare say that Rick! Flares are coming back in! I read it in my horoscope!",
  "Let's raise a People's Army and seize control of the State!",
  "Oh no! The front door's exploded!",
  "Honestly! Whenever anything explodes in this house it's always blame Vyvyan!",
  "Cough! Cough! Splutter! Cor, an exploding front door! Stone the crows, the missus will never believe this 'un!",
  "A package from the Twansvaal! How stwange!",
  "WILL YOU SHUT UP PLEASE!!!!!!!",
  "Little squirt! He does one advert and he thinks he's Dustin Hoffman!",
  "Oh God, I've got to stop sniffing this Ajax!",
  "Oh! Oh! So you've taken to snooping around other people's bedrooms, have you Neil? Grubbing about and planting evidence of transvesticism, so as to topple me from my position as most popular member of the flat! Well it won't work! I've never seen that dress before in my life!",
  "And all those murders you done",
  "We wish to engage you as ship's cook and concubine",
  "Oh that's right Vyvyan, if the mountain won't come to Mohammed, smash the drawing room to pieces! That's very Buddhist, isn't it?",
  "So, what's it to be first then, dear? Head in a vice? Knitting needle in the ear? Or red hot poker up the jacksie?",
  "She's talking about period pains!",
  "I've got a crucifix and I'm not afraid to use it!",
  "No, this is some kind of misunderstanding! I'm not a vampire! I'm a driving instructor! From Johannesburg!",
  "Approaching a humpback bridge, you should slow down and check in both rear view mirrors. If nobody is behind you should RIP OUT THE VIRGIN'S THROAT!",
  "Anyway 'round about now, I usually have a Pot Noodle! It's a tasty... Ummm! Doesn't that look good! It's a tasty delicious little snack! Ummmm! Let's try some, shall we? Doesn't that look absolutely yumscious! Ohhhh! Let's try some, shall we?",
  "Just try telling that to some of the foxy chicks who owe me favours!",
  "He's gonna turn us into vampires, and we'll all be dead, and yet still alive... like Leonard Cohen!",
  "I thought you were Australian, like David Bowie!",
  "It's funny, but being ill makes me lose my usual tolerant and easy-going approach to communal living",
  "Thanks, Vyv. That petrol bomb's really cleared my sinuses",
  "Dear Mr. Echo...",
  "What's this fish doing in my bed?",
  "We've got to keep the bogeys off the wall!",
  "You can't clean the toilet, Neil. It'll lose all its character!",
  "No way, Harpic! No way, Dot! All that Blue Loo scene is for squares. One thing's for sure, Neil. When Cliff Richard wrote 'Wired for Sound', no way was he sitting on a clean lavatory!",
  "No, I live on The Limit, Vyvyan. The Limit. Because I'm a Rider at the Gates of Dawn and I take no prisoners",
  "What's Domestos?",
  "180 pound worth of Durex, please! Oh sorry! FOrce of habit!",
  "My brain's exploded! My brain's exploded!!!",
  "Neil, if you don't stop sneezing by the time I count three, I'mgoing to cut your bottoms off and ram them up your nose",
  "Goodness, how exciting! Are you an anarchist?",
  "Thanks, Doc?! Are you being sar-carstic or something, my son? That's one of my least favorite things, that happens to be. Sar-carsm",
  "Ha ha! Up yours, ugly!",
  "All hail McVyvyan, Thane of Corridor!",
  "All hail McVyvyan, Thane of the Outside Toilet, and that little gravelly patch next to the garden shed",
  "You'll have to watch out for me because I'm a bit nutty. Aren't I, everybody?! A bit nutty?",
  "Come on, sir. Don't be silly! We're the only kidds in Britain who never say fu...",
  "NO!! No! We're not watching the bloody Good Life!! Bloody bloody bloody!! I hate it!! It's so bloody nice! Felicity 'Treacle' Kendall and Richard 'Sugar-Flavored-Snot' Briars!! What do they do now?! Chocolate bloody Button ads, that's what!! They're just a couple of reactionary stereotypes, confirming the myth that everyone in Britain is a lovable, middle-class eccentric - and I - HATE - THEM!",
  "Felicity Kendall is sweetly pretty, and just what a real girlie should be",
  "Good grief, Christine, it'd be pretty bloody super to have a snog in a place like this! What do you think, Neil?",
  "We sow the seed, right. Nature grows the seed, and then, we eat the seed!",
  "Oh, God! Oh, God, I've killed a hippie! I've killed a hippie, and now I'll have to pay. Oh, God. Vyvyan's bound to tell on me, and I'll get sent to prison and raped in the shower by Mr. Big who's in with the warders!",
  "Well, listen, absolutely nobody, I don't care who they are, is doing a two-ton pooh outside of my front door!",
  "What a load of old crap! It's not a gnome! It's a hippie he's just killed. He's just killed a hippie, everybody!!",
  "Cor, that looked just like a negative reality inversion, didn't it?",
  "Oh, People's Poet. Don't die! We'll kill ourselves if you do! But first, we're going to take off all our clothes!",
  "Stop having a wet dream, you little pervy! You're supposed to be racked with remorse!",
  "All annual profits to be donated to the Brothers of the Soil commune in Wales, England? All petroleum and oil to be sold at a retail price of 2p a gallon? All oil wells to be given, tax free, to anyone really nice you can find?!",
  "Would you care for a cup of herbal tea?",
  "Listen! This company's been doing some pretty heavy things over the years, right. And it's gotta start getting beautiful or this planet's heading for oblivion!",
  "I am disfigured for life! I am the Elephant Man!",
  "Who invented the internal combustion engine? Was it Porky the Pig?",
  "Look out, Michaelangelo, here comes the new piggie Renaissance!",
  "I find the idea of spending a night with you completely revolting!",
  "Anyway, it just goes to show you, Neil. Even when I'm unconscious, I can pick up the birds. I mean, forge meaningful relationships with birds...chicks...tarts...women. Women!",
  "At one stage, she even took her bwa off!"
  "It's a nice day for it, isn't it? Oh, no, I didn't mean for It. I meant, it's a nice day for weather",
  "I know what you're thinking, baby. And if I was the telly, you'd think I was talking in centimetres",
  "Sounds like the kind of name someone would give to someone who looks as if they'd been to Hell and back, isn't it?",
  "Get down and groove! We dance all day in this house!",
  "Rick, you bloody liar! You said you done it to her... He said he done it to you!",
  "I am not a virgin! I am not a virgin!",
  "Ah, you're a strapping young lad. Why don't you come sit on your Uncle Billy's knee?",
  "Good afternoon. This is the objective and strictly impartial BBC World Service, operating on behalf of the Conservative Party",
  "All right, if I'm a virgin, how come I know what a girl's bottom looks like?",
  "Strange thing is, Rik's right! That hippie really does pong!",
  "Please, please, can we get on with it? What's all the fuss about? It's only Neil, for Cliff's sake!",
  "Where were we? Oh, yes. Virgin!",
  "Oh, that's beautiful. Hippie knight",
  "Vyv! Where did you get that howitzer?!",
  "I bet, in one second, both of my legs will fall off!",
  "Oh, no! I'll die if I miss Scooby Doo!",
  "When you said panic, I didn't think you meant hang me.",
  "Cut his head off, yeah!",
  "But unfortunately, she can't be with us tonight, can she? No! Because she's not very lovely at the moment, is she? No! Because she's got the plague at the moment, doesn't she?! And her face is one enormous bag of pus!",
  "Would you like some live scampi in your britches?",
  "Would you like to have your eyes sucked out by a goat and replaced with some hot toffee apples?",
  "Do you think ants go to discos?",
  "Hey, doesn't it remind you of when you were little, and you used to sit in the garden in only your underpants? And you used to put loads and loads of fruit down them and pretend to be pirates?",
  "It was horrible. I sat in the big hall and put my pocket of Polos on the desk. And my spare pencil and my support gonk. And my chewing gum and my extra pen. And my extra Polos and my lucky gonk. And my pencil sharpener shaped like a cream cracker. And more gonks with a packet of Polos in each. And lead for my retractable pencil. And my retractable pencil. And spare lead for my retractable pencil. And chewing gum and pencils and pens and more gonks, and the guy says 'Stop writing, please!'",
  "Shut up Neil, you ugly poo-faced git!",
  "What's ugly, smelly, boring, and is standing in front of me called Neil?",
  "Your father's right. Don't put your tongue in Rover's ear, dear. It's very unhygienic",
  "Even mindless violence seems boring today",
  "Strange that such a ruthless and sadistic maniac as Vyvyan should care for a begonia!",
  "What about Jelly Botty, where you have to eat 18 curries?",
  "No, no, he spells it with a silent P",
  "Oh, yes! Oh, yes! Tee-hee Vyvyan, very funny, must be at least 5 minutes since you made that joke....I don't think!",
  "Don't think I don't know exactly who drew that thig-a-ma-jig on the back of my Curriculum Vitae!",
  "Are you a 12th century druid and political activist?",
  "Do you make an enormous about of money by sticking your fist up a duck's bottom?",
  "Now, you knew that anyway, and we don't care, so where's the surprise?",
  "Can a cake dance? Will a cake get you drunk? Will a cake let you put your hand up its jumper?",
  "I was drinking something gloomy. And the girl just looked straight through me. So I had a pint of Hawk and now she's gonna screw me",
  "Shut up, or I'll tell everyone in this room that you've got an iron-on cartoon worm on the front of your Y-fronts that says 'Girl Bait'",
  "Did I say kiss you on the bottom? Oh, beg your pardon. I meant to say, stick a pick axe through your spinal column!",
  "I'm very sober, and very very bored!",
  "Yeah, shut up, you fascist Tories! Nobody tells me what time to go to bed!",
  "Go to bed, spotty!",
  "I suppose it is a bit childish to have aeroplanes on your wallpaper. But they are blue, and I am a boy! At least I was the last time I looked!",
  "Oh, some sod broke your chair. That's what happens when you have parties. That's another 27 pounds you owe me!",
  "Is this house a wildlife park? Do we say, 'I've seen the elephants at Jerzei's house?' No, we don't!",
  "Let me introduce myself. I'm God. You really didn't expect me to be a woman, now, did you?",
  "I'll bloody well make his body talk in a minute!",
  "Thatcher's Britain. Thatcher's bloody Britain! Look at me. I'm young, I'm pretty. I've got 5 O Levels. Bloomin' good grades as well, considering I didn't do a sod of work cause I'm so hard!",
  "I'm gorgeous! I am sex! Women want me and they're prepared to pay!",
  "Bloody hell! Give them a uniform and they think they're Hitler!",
  "You have come bottom in ze whole vorld!",
  "C'mon, let's do it! White Riot. Stand Down Margaret. I'm a child of recession, I've got hate in my eyes. Ask for me tomorrow and I'll be gone cause I've got a one-way ticket to oblivion and I'm going to raise hell getting there!",
  "I'm not putting my head where some horrid girlie's bottom's been!",
  "I didn't get them at Tesco's, OK?",
  "Right on. I'm aboard the Freedom Bus, heading for Good Time City and I haven't even paid my fare!",
  "Look, what we really need is to pick up some great-looking girls whose car has broken down, and they can do all the cooking and cleaning!",
  "We can do just exactly whatever we want to do! And you know why? Because we're Young Ones. Bachelor boys! Crazy, mad, wild-eyed, big-bottomed anarchists!!",
  "Look out! Cliff!!!!",
  "Phew! That was close!"
];

document.addEventListener("DOMContentLoaded", () => {
  const quoteButton = document.getElementById("new-quote");
  const quoteDisplay = document.getElementById("quote");
  const twitterButton = document.getElementById("twitter-share");
  const facebookButton = document.getElementById("facebook-share");
  quoteButton.addEventListener("click", () => {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const newQuote = quotes[randomIndex];
    quoteDisplay.textContent = newQuote;
  });
  twitterButton.addEventListener("click", () => {
    const text = encodeURIComponent(quoteDisplay.textContent + " #TheYoungOnes");
    const twitterUrl = `https://twitter.com/intent/tweet?text=${text}`;
    window.open(twitterUrl, "_blank");
  });
  facebookButton.addEventListener("click", () => {
    const text = encodeURIComponent(quoteDisplay.textContent);
    const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=&quote=${text}`;
    window.open(facebookUrl, "_blank");
  });
});

























